management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,metrics
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true