name: spring-boot-webflux
runtime:
  name: nodejs
  options:
    # See https://github.com/TypeStrong/ts-node/issues/1007
    nodeargs: "--loader ts-node/esm --no-warnings --experimental-specifier-resolution=node"
description: Spring Experiement
